services:
  - type: web
    name: suvidha
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn suvidha:app"
    envVars:
      - key: PORT
        value: 10000  # You can remove this if Render dynamically assigns it
